name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build artifact
        run: |
          zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'newtrail21'  # Replace with your Azure App Service name
